# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('accept_time', models.DateTimeField(blank=True, null=True)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=192)),
                ('statement', models.TextField(blank=True)),
                ('time_limit', models.IntegerField(default=1000)),
                ('scene_type', models.CharField(choices=[('game', 'Game'), ('combat', 'Combat')], max_length=30)),
                ('html_analysis_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_set', to='program.Code')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_set', to='program.Code')),
                ('solutions', models.ManyToManyField(to='judge.Solution')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene.Scene'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='code1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code1_set', to='judge.Solution'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='code2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code2_set', to='judge.Solution'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='report0_judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report0_judge_set', to='program.RunningReport'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='report1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report1_set', to='program.RunningReport'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='report2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report2_set', to='program.RunningReport'),
        ),
    ]
