# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='belong_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scene.Scene'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='code1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code1_set', to='judge.CombatSolution'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='code2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code2_set', to='judge.CombatSolution'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='report0_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report0_judge_set', to='program.RunningReport'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='report1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report1_set', to='program.RunningReport'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='report2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report2_set', to='program.RunningReport'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='solutions',
            field=models.ManyToManyField(blank=True, to='judge.Solution'),
        ),
    ]
