# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CombatSolution',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.Solution')),
                ('rating', models.IntegerField(default=0)),
            ],
            bases=('judge.solution',),
        ),
        migrations.CreateModel(
            name='GameSolution',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='judge.Solution')),
                ('score', models.PositiveIntegerField(default=0)),
                ('judge_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_report_set', to='program.RunningReport')),
                ('user_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report_set', to='program.RunningReport')),
            ],
            bases=('judge.solution',),
        ),
        migrations.AddField(
            model_name='solution',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solution',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Code'),
        ),
    ]
